language: cpp
compiler:
  - gcc
#  - clang
sudo: required
dist: trusty

install:
  # CppCheck
  - sudo apt-get install -qq cppcheck
  # Pybind11
  - sudo apt-get install python-pip
  - python3 -m pip install pybind11

script:
  # Runs compilation, cppcheck, tests and coverage collection
  - make develcheck

after_success:
    # codecov.io
    - bash <(curl -s https://codecov.io/bash) -X gcov -f 'test/gcov/*.gcov'

notifications:
  email:
    recipients:
      - d.desensi.software@gmail.com
    on_success: never # default: change
    on_failure: always # default: always